name: multi_grocery_shop
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  firebase_storage: ^11.0.5
  cloud_firestore: ^4.0.5
  image_picker: ^0.8.6
  cached_network_image: ^3.2.2
  shimmer_animation: ^2.1.0+1
  country_state_city_picker: ^1.2.8
  uuid: ^3.0.6
  flutter_easyloading: ^3.0.5
  flutterfire_ui: ^0.4.3+14
  provider: ^6.0.4
  date_time_picker: ^2.1.0
  date_time_format: ^2.0.1
  date_format: ^2.0.7
  font_awesome_flutter: ^10.2.1
  chart_sparkline: ^1.0.11
  chips_choice: ^3.0.0
  custom_rating_bar: ^2.0.4
  smooth_star_rating_null_safety: ^1.0.4+2
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^2.0.0
  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  



dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/


  fonts:
    - family: Brand-Bold
      fonts:
        - asset: assets/fonts/GemunuLibre-Bold.ttf
          
       
       
    - family: Semi-Bold
      fonts:
        - asset: assets/fonts/GemunuLibre-SemiBold.ttf
       
         
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
